server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 1. Ruta Pública para Autenticación (Auth MS)
        - id: auth-ms
          uri: lb://auth-ms
          predicates:
            - Path=/api/auth/**

        # 2. Ruta Protegida: Ventas
        - id: ventas-ms
          uri: lb://ventas-ms
          predicates:
            - Path=/api/ventas/**
          filters:
            - AuthenticationFilter

        # 3. Ruta Protegida: Despachos
        - id: despachos-ms
          uri: lb://despachos-ms
          predicates:
            - Path=/api/despachos/**
          filters:
            - AuthenticationFilter

        # 4. Ruta Protegida: Devoluciones
        - id: devoluciones-ms
          uri: lb://devoluciones-ms
          predicates:
            - Path=/api/devoluciones/**
          filters:
            - AuthenticationFilter

        # 5. Ruta Protegida: Productos (Catálogo)
        - id: productos-ms
          uri: lb://productos-ms
          predicates:
            - Path=/api/productos/**
          filters:
            - AuthenticationFilter

        # 6. Ruta Protegida: Clientes
        - id: clientes-ms
          uri: lb://clientes-ms
          predicates:
            - Path=/api/clientes/**
          filters:
            - AuthenticationFilter

        # 7. Ruta Protegida: Proveedores
        - id: proveedores-ms
          uri: lb://proveedores-ms
          predicates:
            - Path=/api/proveedores/**
          filters:
            - AuthenticationFilter

        # 8. Ruta Protegida: Vendedores (Personal y Comisiones)
        - id: vendedores-ms
          uri: lb://vendedores-ms
          predicates:
            - Path=/api/vendedores/**
          filters:
            - AuthenticationFilter

        # 9. Ruta Protegida: Inventario (Stock de Bodega)
        - id: inventario-ms
          uri: lb://inventario-ms
          predicates:
            - Path=/api/inventario/**
          filters:
            - AuthenticationFilter

        # 10. Ruta Protegida: Compras (Abastecimiento)
        - id: compras-ms
          uri: lb://compras-ms
          predicates:
            - Path=/api/compras/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# clave secreta para la validación del filtro
jwt:
  secret: Zm9ybXVsYS1zZWNyZXRhLWRlLWxvcy1ncmlmb3MtMjAyNi10b2RvZ3JpZm9zLWV4YW1lbg==